---
title: "Replicate results"
output: html_document
date: "2024-10-16"
---
# load data
```{r}
# load Carl's data
setwd("~/GitHub/BCH-GBS/0.Raw_Data")
data_Carl <- read.csv("GBS_Mastersheet_Carl.csv") |> 
  filter(Sample!="")|>
  select(-ID)|>
  mutate(Meningitis= ifelse(isolated_from == "blood", 0, 1))
colnames(data_Carl) <- paste0("Carl_", colnames(data_Carl))
data_Carl <- data_Carl|> 
  rename("ID"="Carl_Sample")

# load my data
setwd("~/GitHub/BCH-GBS/2.Statistical_Analysis")
data_Lea <- read.xlsx("Clinical_Genomic_data.xlsx", sheetIndex = 1) |>
  filter(! ID %in% c("1_S1","32_S32","35_S35","81_S81"))|> 
  mutate(ICU = ifelse(Admission_loc=="ICU", 1,0))
```

# Compare samples
```{r}
# Number of patients 
nrow(data_Carl)
nrow(data_Lea)

# Which samples are in Carl's dataset but not mine ? 
data_Carl |> filter(! ID %in% data_Lea$ID)|> pull(ID)

# Which samples are in my dataset but Carl's ? 
data_Lea |> filter(! ID %in% data_Carl$ID)|> pull(ID)
```


# Dates
```{r}
data_both <- left_join(data_Lea, data_Carl)

# Year of diagnosis
data_both |> 
  filter(Carl_Diagnosis_date != year(Date.of.cx))

# days at diagnosis
data_both |> 
  filter(Carl_days_at_dx != days_at_dx)|> 
  select(ID, Carl_days_at_dx, days_at_dx, Date.of.cx, DOB)|> 
  mutate(test= Date.of.cx- DOB)

# Age_cat
data_both |> 
  mutate(Carl_Age_cat = ifelse(Carl_Age_cat =="90days-17yr", "Older Children (1-18 years)", Carl_Age_cat))|> 
  mutate(Carl_Age_cat = ifelse(Carl_Age_cat =="18-39yrs", "Adults", Carl_Age_cat))|>
  filter(Carl_Age_cat != Age_cat)|> 
  select(ID, Carl_Age_cat, Age_cat, days_at_dx)
```
# Clinical characteristics
```{r}
# Meningitis
data_both |> 
  filter(Carl_Meningitis != Meningitis)|> 
  select(ID, Carl_Meningitis, Meningitis, Carl_isolated_from, isolated_from)

# isolated_from
data_both |> 
  mutate(Carl_isolated_from = ifelse(Carl_isolated_from =="both", "blood; csf", Carl_isolated_from))|> 
  filter(Carl_isolated_from != isolated_from)|> 
  select(ID, Carl_Meningitis, Meningitis, Carl_isolated_from, isolated_from)

# ICU
data_both |> 
  mutate(Carl_Admission_loc = ifelse(Carl_Admission_loc =="other", 0, 1))|> 
  filter(Carl_Admission_loc != ICU)|> 
  select(ID, Carl_Admission_loc, ICU)

# Hb
data_both |> 
  filter(Carl_Hb != Hb)|> 
  select(ID, Carl_Hb, Hb)

# WBC
data_both |> 
  filter(Carl_WBC != WBC)|> 
  select(ID, Carl_WBC, WBC)

# ANC
data_both |> 
  filter(Carl_ANC != ANC)|> 
  select(ID, Carl_ANC, ANC)

# platelet
data_both |> 
  filter(Carl_platelet != platelet)|> 
  select(ID, Carl_platelet, platelet)

# Leukocytosis
data_both |> 
  filter(Carl_Leucocytosis != Leukocytosis)|> 
  select(ID, Carl_Leucocytosis, Leukocytosis, ALC)

# Leucopenia
data_both |> 
  filter(Carl_Leucopenia != Leukopenia)|> 
  select(ID, Carl_Leucopenia, Leukopenia, ALC)


# Leucopenia
data_both |> 
  filter(Carl_Neutropenia != Neutropenia)|> 
  select(ID, Carl_Neutropenia, Neutropenia, Carl_ANC, ANC)

```

