---
title: "Vax_coverage_BCH"
output: html_document
date: "2023-09-18"
---

```{r}
  # Clean environment
  rm( list = ls() )
  
  # load libraries
library(tidyverse)

# load metadata
setwd("~/Harvard/Research/GBS/Figures")
metadata <- read.csv("metadata_BCH_05292024.csv") |> 
  mutate(Age_cat=factor(Age_cat, levels=c("EOD", "LOD","VLOD", "older children (1-17yr)", "adults (>18yr)")))
```


# BCH Capsular polysaccharise and Protein vaccine potential coverage by Age group 
```{r}
BCH_vax_Age_tab <- metadata |>
  group_by(Age_cat) |>
  summarise(n=n(),
            trivalent= paste(sum(Serotype %in% c("Ia", "Ib", "III")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "III"))/n), "%)",sep=""), 
            hexavalent = paste(sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V"))/n), "%)",sep=""),
            RIB=paste(sum(Surface_protein.RIB), " (", round(100*sum(Surface_protein.RIB)/n), "%)",sep=""),
            ALPHA=paste(sum(Surface_protein.ALPHA), " (", round(100*sum(Surface_protein.ALPHA)/n), "%)",sep=""),
            ALP1=paste(sum(Surface_protein.ALP1), " (", round(100*sum(Surface_protein.ALP1)/n), "%)",sep=""),
            ALP23=paste(sum(Surface_protein.ALP23), " (", round(100*sum(Surface_protein.ALP23)/n), "%)",sep=""),
            ALPHA_RIB=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)/n), "%)",sep=""),
            ALP1_ALP23=paste(sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            ALPHA_RIB_ALP1_ALP23=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            PI1=paste(sum(Surface_protein.PI1), " (", round(100*sum(Surface_protein.PI1!=0)/n), "%)",sep=""),
            PI2a=paste(sum(Surface_protein.PI2A1+Surface_protein.PI2A2), " (", round(100*sum(Surface_protein.PI2A1+Surface_protein.PI2A2)/n), "%)",sep=""),
            PI2b=paste(sum(Surface_protein.PI2B), " (", round(100*sum(Surface_protein.PI2B)/n), "%)",sep=""),
            PI1_PI2a_PI2b=paste(sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)," (", round(100*sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)/n), "%)",sep=""),
            SRR1=paste(sum(Surface_protein.SRR1), " (", round(100*sum(Surface_protein.SRR1)/n), "%)",sep=""),
            SRR2=paste(sum(Surface_protein.SRR2), " (", round(100*sum(Surface_protein.SRR2)/n), "%)",sep=""),
            SRR1_SRR2=paste(sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)," (", round(100*sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)/n), "%)",sep="") ,
            Sip=paste(sum(Sip_gene_presence_absence)," (", round(100*sum(Sip_gene_presence_absence)/n), "%)",sep=""),
            C5a=paste(sum(Virulence_factor.C5a_peptidase)," (", round(100*sum(Virulence_factor.C5a_peptidase)/n), "%)",sep=""),
            Lmb=paste(sum(Virulence_factor.Lmb)," (", round(100*sum(Virulence_factor.Lmb)/n), "%)",sep=""),
            FbsB=paste(sum(Virulence_factor.FbsB)," (", round(100*sum(Virulence_factor.FbsB)/n), "%)",sep=""))



BCH_vax_total_tab <- metadata |>
  summarise(n=n(),
            trivalent= paste(sum(Serotype %in% c("Ia", "Ib", "III")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "III"))/n), "%)",sep=""), 
            hexavalent = paste(sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V"))/n), "%)",sep=""),
            RIB=paste(sum(Surface_protein.RIB), " (", round(100*sum(Surface_protein.RIB)/n), "%)",sep=""),
            ALPHA=paste(sum(Surface_protein.ALPHA), " (", round(100*sum(Surface_protein.ALPHA)/n), "%)",sep=""),
            ALP1=paste(sum(Surface_protein.ALP1), " (", round(100*sum(Surface_protein.ALP1)/n), "%)",sep=""),
            ALP23=paste(sum(Surface_protein.ALP23), " (", round(100*sum(Surface_protein.ALP23)/n), "%)",sep=""),
            ALPHA_RIB=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)/n), "%)",sep=""),
            ALP1_ALP23=paste(sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            ALPHA_RIB_ALP1_ALP23=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            PI1=paste(sum(Surface_protein.PI1!=0), " (", round(100*sum(Surface_protein.PI1!=0)/n), "%)",sep=""),
            PI2a=paste(sum(Surface_protein.PI2A1+Surface_protein.PI2A2), " (", round(100*sum(Surface_protein.PI2A1+Surface_protein.PI2A2)/n), "%)",sep=""),
            PI2b=paste(sum(Surface_protein.PI2B), " (", round(100*sum(Surface_protein.PI2B)/n), "%)",sep=""),
            PI1_PI2a_PI2b=paste(sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)," (", round(100*sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)/n), "%)",sep=""),
            SRR1=paste(sum(Surface_protein.SRR1), " (", round(100*sum(Surface_protein.SRR1)/n), "%)",sep=""),
            SRR2=paste(sum(Surface_protein.SRR2), " (", round(100*sum(Surface_protein.SRR2)/n), "%)",sep=""),
            SRR1_SRR2=paste(sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)," (", round(100*sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)/n), "%)",sep="") ,
            Sip=paste(sum(Sip_gene_presence_absence)," (", round(100*sum(Sip_gene_presence_absence)/n), "%)",sep=""),
            C5a=paste(sum(Virulence_factor.C5a_peptidase)," (", round(100*sum(Virulence_factor.C5a_peptidase)/n), "%)",sep=""),
            Lmb=paste(sum(Virulence_factor.Lmb)," (", round(100*sum(Virulence_factor.Lmb)/n), "%)",sep=""),
            FbsB=paste(sum(Virulence_factor.FbsB)," (", round(100*sum(Virulence_factor.FbsB)/n), "%)",sep=""))


BCH_vax_tab <- t(rbind(BCH_vax_Age_tab, BCH_vax_total_tab |> mutate(Age_cat="Total")))
colnames(BCH_vax_tab) <- BCH_vax_tab[1,]
BCH_vax_tab <- BCH_vax_tab[-1,]
as.data.frame(BCH_vax_tab)

```


# BCH Capsular polysaccharise and Protein vaccine potential coverage by Age group 
```{r}
BCH_vax_CC_tab <- metadata |>
  group_by(CC) |>
  summarise(n=n(),
            trivalent= paste(sum(Serotype %in% c("Ia", "Ib", "III")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "III"))/n), "%)",sep=""), 
            hexavalent = paste(sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V")), " (", round(100* sum(Serotype %in% c("Ia", "Ib", "II","III", "IV", "V"))/n), "%)",sep=""),
            RIB=paste(sum(Surface_protein.RIB), " (", round(100*sum(Surface_protein.RIB)/n), "%)",sep=""),
            ALPHA=paste(sum(Surface_protein.ALPHA), " (", round(100*sum(Surface_protein.ALPHA)/n), "%)",sep=""),
            ALP1=paste(sum(Surface_protein.ALP1), " (", round(100*sum(Surface_protein.ALP1)/n), "%)",sep=""),
            ALP23=paste(sum(Surface_protein.ALP23), " (", round(100*sum(Surface_protein.ALP23)/n), "%)",sep=""),
            ALPHA_RIB=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB!=0)/n), "%)",sep=""),
            ALP1_ALP23=paste(sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            ALPHA_RIB_ALP1_ALP23=paste(sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)," (", round(100*sum(Surface_protein.ALPHA+Surface_protein.RIB+Surface_protein.ALP1+Surface_protein.ALP23!=0)/n), "%)",sep=""),
            PI1=paste(sum(Surface_protein.PI1), " (", round(100*sum(Surface_protein.PI1!=0)/n), "%)",sep=""),
            PI2a=paste(sum(Surface_protein.PI2A1+Surface_protein.PI2A2), " (", round(100*sum(Surface_protein.PI2A1+Surface_protein.PI2A2)/n), "%)",sep=""),
            PI2b=paste(sum(Surface_protein.PI2B), " (", round(100*sum(Surface_protein.PI2B)/n), "%)",sep=""),
            PI1_PI2a_PI2b=paste(sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)," (", round(100*sum(Surface_protein.PI1+Surface_protein.PI2A1+Surface_protein.PI2A2+Surface_protein.PI2B!=0)/n), "%)",sep=""),
            SRR1=paste(sum(Surface_protein.SRR1), " (", round(100*sum(Surface_protein.SRR1)/n), "%)",sep=""),
            SRR2=paste(sum(Surface_protein.SRR2), " (", round(100*sum(Surface_protein.SRR2)/n), "%)",sep=""),
            SRR1_SRR2=paste(sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)," (", round(100*sum(Surface_protein.SRR1+Surface_protein.SRR2!=0)/n), "%)",sep="") ,
            Sip=paste(sum(Sip_gene_presence_absence)," (", round(100*sum(Sip_gene_presence_absence)/n), "%)",sep=""),
            C5a=paste(sum(Virulence_factor.C5a_peptidase)," (", round(100*sum(Virulence_factor.C5a_peptidase)/n), "%)",sep=""),
            Lmb=paste(sum(Virulence_factor.Lmb)," (", round(100*sum(Virulence_factor.Lmb)/n), "%)",sep=""),
            FbsB=paste(sum(Virulence_factor.FbsB)," (", round(100*sum(Virulence_factor.FbsB)/n), "%)",sep=""))



BCH_vax_CC_total_tab <- t(rbind(BCH_vax_CC_tab, BCH_vax_total_tab |> mutate(CC="Total")))
colnames(BCH_vax_CC_total_tab) <- BCH_vax_CC_total_tab[1,]
BCH_vax_CC_total_tab <- BCH_vax_CC_total_tab[-1,]
as.data.frame(BCH_vax_CC_total_tab)

```


